### PR TITLE
Fix vagrant permission denied (publickey) message

### PR DESCRIPTION
**Pull request by kreolll**
Fix vagrant permission denied (publickey) message

### CODE REVIEW

**Comment by ltpitt** [comment]
Hi there!

If you apply this fix then you will login as vagrant user but all the sdk and software was installed for the Ubuntu user and therefore the sdk will not work. 

Can you better explain?

**Comment by kreolll** [comment]
Hello, ltpitt.
Sorry for my english.
Video: https://www.youtube.com/watch?v=Dj50l5zrfKE
By default authorization with authorized_keys works with vagrant user

**Comment by ltpitt** [comment]
This is quite peculiar!

Works on my pc and another user was specifically requesting this...

If you change the code to vagrant then pebble-sdk works fine for you?

**Comment by kreolll** [comment]
Hello, Davide.
Yes, its works correctly with vagrant user in Vagrantfile

**Comment by ltpitt** [comment]
Thanks for your contribution!

**Comment by kreolll** [comment]
Thanks for you too!

**Pull request merged**
